# Generated by Django 3.2 on 2021-04-11 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kapela', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instrument', models.CharField(max_length=30, verbose_name='Instrument')),
                ('member_since', models.DateField(verbose_name='Member since')),
                ('member_to', models.DateField(blank=True, null=True, verbose_name='*Member to')),
            ],
            options={
                'ordering': ['instrument'],
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=30, verbose_name='Last name')),
                ('first_name', models.CharField(max_length=45, verbose_name='First name')),
                ('birthdate', models.DateField(help_text='Please use the following format: <em>YYYY-MM-DD</em>.', verbose_name='Birthdate')),
                ('biography', models.TextField(blank=True, max_length=250, null=True, verbose_name='Biography')),
            ],
            options={
                'ordering': ['last_name'],
            },
        ),
    ]
