# Generated by Django 3.2 on 2021-04-11 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kapela', '0002_member_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='band',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='kapela.band'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='person',
            name='biography',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Biography'),
        ),
    ]
