# Generated by Django 3.2 on 2021-04-11 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kapela', '0003_auto_20210411_1243'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='person_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='kapela.person'),
            preserve_default=False,
        ),
    ]
