# Generated by Django 3.2 on 2021-04-12 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kapela', '0004_member_person_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='member_since',
            field=models.DateField(help_text='Please use the following format: <em>YYYY-MM-DD</em>.', verbose_name='Member since'),
        ),
        migrations.AlterField(
            model_name='member',
            name='member_to',
            field=models.DateField(blank=True, help_text='Please use the following format: <em>YYYY-MM-DD</em>.', null=True, verbose_name='*Member to'),
        ),
    ]
