# Generated by Django 3.2 on 2021-05-04 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kapela', '0005_auto_20210412_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='band',
            name='history',
            field=models.TextField(blank=True, null=True, verbose_name='History'),
        ),
    ]
