# Generated by Django 3.2 on 2021-05-04 12:48

from django.db import migrations, models
import kapela.models


class Migration(migrations.Migration):

    dependencies = [
        ('kapela', '0006_band_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='band',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to=kapela.models.poster_path, verbose_name='Poster'),
        ),
    ]
