# Generated by Django 3.2 on 2021-05-04 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kapela', '0007_band_poster'),
    ]

    operations = [
        migrations.RenameField(
            model_name='band',
            old_name='history',
            new_name='about',
        ),
    ]
