# Generated by Django 3.2 on 2021-05-04 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kapela', '0008_rename_history_band_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='band',
            name='about',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='About'),
        ),
    ]
